version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: bion_user
      POSTGRES_PASSWORD: 0xoavf78NKtWENO5Ui7bFCGZoGCoaTWG
      POSTGRES_DB: bion
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - C:/data:/var/lib/postgresql/data
    networks:
      - nat
  
  registry-server:
    image: bion0625/registry-server:v1
    environment:
      TZ: Asia/Seoul
    ports:
      - "8761:8761"
    networks:
      - nat
  
  admin-server:
    image: bion0625/admin-server:v1
    environment:
      TZ: Asia/Seoul
    ports:
      - "9090:9090"
    networks:
      - nat
  
  trade-service:
    image: bion0625/trade-service:v1
    environment:
      - ACTIVE=prd
      - TZ=Asia/Seoul
    ports:
      - "8080:8080"
    networks:
      - nat
    depends_on:
      - postgres
  
  edge-server:
    image: bion0625/edge-server:v1
    ports:
      - "8085:8085"
    networks:
      - nat

volumes:
  postgres_data:

networks:
  nat:
    driver: bridge